name: update on push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Set up SSH key
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H 51.222.111.183 > ~/.ssh/known_hosts

    - name: Run the script on the remote VM
      run: |
        ssh ubuntu@51.222.111.183 "cd /home/ubuntu/backend/ && git pull origin master && git fetch origin && cd /home/ubuntu && docker-compose down && docker-compose up --build -d backend"

